=== GNOME/pybliographer/doc/design/txdata.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!--                    General attributes                         -->
<!--                    Attributes common to most elements         -->
<!ENTITY % genattr      "
        n          CDATA #IMPLIED
        type       CDATA #IMPLIED
        valid      CDATA #IMPLIED
        id         ID    #IMPLIED
        kind       CDATA #IMPLIED               "                    >
        

<!--                    uml related information                    -->
<!--                    presently only use cases                   -->

<!ELEMENT  uml          ((classinfo|usecase)*)                       >

<!--                    Class information                          -->
<!--                    textual overview of classes                -->
<!ELEMENT  classinfo    (title, summary, attribute*, operation*,
                         invariant*, note*, related*  )              >
<!ATTLIST  classinfo
         %genattr;
>
<!--                    title                                      -->
<!ELEMENT  title        (#PCDATA)                                    >

<!--                    summary                                    -->
<!ELEMENT  summary      (#PCDATA)                                    >

<!--                    Class attributes                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  attributes   ((attribute|note)*)                          >

<!--                    attribute                                  -->
<!ELEMENT  attribute    (#PCDATA)                                    >

<!--                    Usecase description (text)                 -->
<!ELEMENT  usecase      (title, summary, actor+, context?,
                           precondition, postcondition, input?, 
                           result?,  error*, sequence*, note*,
                           related* )                                >




<!--                    Note                                       -->
<!--                    any textual addition or explanation        -->
<!ELEMENT  note         (#PCDATA)                                    >

<!--                    Class operations                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  operations   ((operation|note)*)                          >

<!--                    Class operation                            -->
<!--                    not yet defined                            -->
<!ELEMENT  operation    (#PCDATA)                                    >

<!--                    Class invariants                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  invariants   ((invariant|note)*)                          >

<!--                    Class invariant                            -->
<!--                    not yet defined                            -->
<!ELEMENT  invariant    (#PCDATA)                                    >

<!--                    Notes                                      -->
<!--                    any sosequence of additions and
                        explanations                               -->
<!ELEMENT  notes        (note*)                                      >


<!--                    precondition                               -->
<!ELEMENT  precondition (#PCDATA)                                    >

<!--                    postcondition                              -->
<!ELEMENT  postcondition  (#PCDATA)                                  >

<!--                    error                                      -->
<!ELEMENT  error        (title?, summary?, precondition?,
                         postcondition?)                             >

<!--                    actor                                      -->
<!ELEMENT  actor       (#PCDATA)                                    >

<!--                    sequence                                   -->
<!ELEMENT  sequence     (title?,summary?,(item,note*)+)              >


<!--                    li                                         -->
<!ELEMENT  li           (#PCDATA)                                    >

<!--                    dt                                         -->
<!ELEMENT  dt           (#PCDATA)                                    >

<!--                    di                                         -->
<!ELEMENT  di           (#PCDATA)                                    >

<!--                    trigger                                    -->
<!ELEMENT  trigger      (#PCDATA)                                    >


<!--                    UML Glossary                               -->
<!--                    incomplete                                 -->
<!ELEMENT  glossary     (GlossEntry+)                                >


<!--                    Glossary entry                             -->
<!--                    incomplete                                 -->
<!ELEMENT  GlossEntry   (GlossTerm, Acronym?, Abbrev?,
                         (GlossSee | GlossDef+), GlossSeeAlso*)      >


<!--                    Term                                       -->
<!--                    a simple string?                           -->
<!ELEMENT  term         (#PCDATA)                                    >


<!--                    Docbook GlossTerm                          -->
<!--                    Term outside a Glossary that is defined in
                        some GlossEntry; term within a GlossEntry 
                        that is defined by that GlossEntry         -->
<!ELEMENT  GlossTerm    (#PCDATA)                                    >

<!--                    Docbook Acronym                            -->
<!--                    Pronounceable contraction of initials      -->
<!ELEMENT  Acronym      (#PCDATA)                                    >

<!--                    Docbook Abbrev                             -->
<!--                    Abbreviation, especially one followed by a
                        period                                     -->
<!ELEMENT  Abbrev       (#PCDATA)                                     >


<!--                    Docbook GlossSee               -->
<!--                    Cross-reference from one GlossEntry to
                        another                                    -->
<!ELEMENT  GlossSee     (#PCDATA|GlossTerm)*                   >

<!--                    Docbook GlossSeeAlso                       -->
<!--                    Cross-reference from one GlossDef to
                        another GlossEntry                         -->
<!ELEMENT  GlossSeeAlso (#PCDATA |  GlossTerm)*                   >


<!--                    Docbook GlossDef                           -->
<!--                    Definition attached to a GlossTerm in a
                        GlossEntry                                 -->
<!ELEMENT  GlossDef     (#PCDATA |  GlossTerm)*                   >


<!--                    Dialogue Interface description             -->
<!--                    Describes a GUI interface                  -->
<!ELEMENT  dialogue     (title, summary?, context?, data*, action*,
                         note*)                                      >
<!ATTLIST  dialogue
        %genattr;
>

<!--                    Context of action, interface               -->
<!--                    Describes context, usage, etc.             -->
<!ELEMENT  context      (#PCDATA)                                    >

<!--                    Data description                           -->
<!--                    Describes data elements of interfaces      -->
<!ELEMENT  data         (label, item, note?)                         >

<!--                    Input description                          -->
<!--                    Describes input data elements              -->
<!ELEMENT  input        (label, item, note?)*                        >

<!--                    Result description                         -->
<!--                    Describes resulting data elements          -->
<!ELEMENT  result       (label, item, note?)*                        >

<!--                    Descriptive Label                          -->
<!--                    Gives the name of data elements etc.       -->
<!ELEMENT  label        (#PCDATA)                                    >

<!--                    Description of Item                        -->
<!--                    Explains the item                          -->
<!ELEMENT  item         (#PCDATA)                                    >

<!--                    Action Description                         -->
<!--                    Associated Actions                         -->
<!ELEMENT  action       (subactions?, label, item, note?)            >

<!--                    Subaction references                       -->
<!--                    Gives actions that are not explained here
                        but possibly nested within the described
                        action                                     -->
<!ELEMENT  subactions   (#PCDATA)                                    >

<!--                    Related information                        -->
<!--                    Indicates related documents                -->
<!ELEMENT  related      (#PCDATA)                                    >

=== GNOME/pybliographer/doc/design/data/gloen_a.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE glossary SYSTEM '../txdata.dtd' >


<glossary buchstabe="A">


  <GlossEntry>
    <GlossTerm>analytic</GlossTerm>
    <GlossDef>
      In the field of bibliography (so called library science), one
      calls analytic a description or record for a work that is
      contained in another bibliographic unit, i.e., an article that is
      published in a (volume of a) journal and not as an individual
      physical unit. In German, one speaks of publications that are
      (un)selbstständig, (in)dependant. 

      Analytic description is usually considered the province of
      database services, not of the library system, so the cataloguing
      rules and standards mostly ignore this topic. 
    </GlossDef>
    <GlossSeeAlso>Collection, Monograph</GlossSeeAlso>
  </GlossEntry>

  <GlossEntry>
    <GlossTerm>
      Anglo-American Cataloguing Rules (second edition, revised)
    </GlossTerm>
    <Abbrev>AACR2R</Abbrev>
    <GlossDef>
      
    </GlossDef>
    <GlossSeeAlso>RAK</GlossSeeAlso>
  </GlossEntry>

</glossary>

=== GNOME/pybliographer/doc/design/data/uc023.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc023' type='standard' lang='en' >

    <title>Preset input
    </title>

    <summary>This usecase groups various ways to simplify data entry.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc007.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc004' type='standard' lang='en' actor="">

  <title>Mark and list Items
  </title>

  <summary>Make a list of items for further processing (e.g., mark
    the items and retrieve them together) 
  </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
  <note></note>
  <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc008.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc008' type='standard' lang='en' >

    <title>Add an action to an item
    </title>

    <summary>An item (or a set of them) is selected for further
    processing, an indicative action is added to them.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/cl_CIndex.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE classinfo SYSTEM '../txdata.dtd' >


<classinfo name="CIndex" type="display controller">
  <title>Index Display
  </title>
  <summary>
    Display a result set (iterator) as an index listing.
  </summary>
  <operation type="signal">add-item</operation>
  <operation type="signal">remove-item</operation>
  <operation type="signal">update-item</operation>
  <operation type="signal">change-size</operation>
  <operation type="signal">set-position</operation>
  <operation type="signal">scroll-position</operation>
  <operation type="signal">update-selection (?)</operation>
  <operation type="signal">accept-dnd (?)</operation>
  
  <operation>add_item : item, iter updates display, ...</operation>
  <operation>update_item : item, iter updates display, ...</operation>
  <operation>delete_item : item, iter updates display, ...</operation>
  <operation>filter_item : item, iter -> bool</operation>
  <operation>display: iter, sort=None... </operation>
  
</classinfo>

=== GNOME/pybliographer/doc/design/data/gloen_i.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE glossary SYSTEM '../txdata.dtd' >


<glossary buchstabe="I">


  <GlossEntry>
    <GlossTerm>Imprint</GlossTerm>
    <GlossSee>Publication Statement</GlossSee>
  </GlossEntry>


  <GlossEntry>
    <GlossTerm>International Standard for Bibliographical
      Description</GlossTerm>
    <Acronym>ISBD</Acronym>
    <GlossDef>
      


      
    </GlossDef>
    <GlossSeeAlso>AACR2R, PI, RAK</GlossSeeAlso>
  </GlossEntry>


</glossary>

=== GNOME/pybliographer/doc/design/data/uc001.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc000' type='standard' lang='en' >

    <title>Simple Search</title>

    <summary>
      A simple search (known item search) is performed.  The result
      set is displayed.
    </summary>
    <actor>Simple user (A)</actor> <situation></situation>
    <precondition>
      A database, folder or result set is given (usually
      defaulted). The item is correctly entered into the database, or
      not available.
    </precondition>
    <postcondition>
      A resultset of item selected is displayed, or an indication of
      empty result set is given.
    </postcondition>

    <sequence>
    <item>Enter the search term, select regexp search and the search
      field, if appropiate.
    </item>
    <item>Start search.</item>
    <item>Receive results or failure indication (should be
    explanatory).</item> 
    <item>Continue with ..... browsing the result set or similar
    activity.</item>
    </sequence>
    <note>For general considerations for this known item search, which
    pertain mostly to the question of database content, as opposed to
    programming, see in particular Eversberg.
    </note>
    <related>
      Interfaces: if_query1
    </related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc002.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >


  <usecase n='uc002' type='standard' lang='en' actor="A">
   <title>Modified Search</title>

  <summary>A search that was not fully satisfying is done again with
    slight variations or on the result set to further reduce it.
  </summary>
  <actor>Standard user</actor>
  <context>
    During a search, frequency unknown. 
  </context>
  <precondition>
    Database is selected, a search as been performed, but was not
    fully satisfying. 
  </precondition>
  <postcondition>
    Results set or error indication
  </postcondition>
    <error>
    </error>
    <sequence>
    <item>Examine result set (or error indication)</item>
    <item>Correct search term (go to index, if needed)</item>
    <item>Narrow or widen search</item>
    <item>Select another database</item>
    <item>restrict search to a result set.</item>
    </sequence>
    <note>
      The particularity here is that the result of the prior search is
      effectively ignored, except when we are narrowing our search. So
      we must distinguish this situation from the other one, that I
      search for a list of authors etc., one after the other, and with
      the intent to combine the results.

  </note>
    <related></related>

  </usecase>
