=== GNOME/pybliographer/doc/design/txdata.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!--                    General attributes                         -->
<!--                    Attributes common to most elements         -->
<!ENTITY % genattr      "
        n          CDATA #IMPLIED
        type       CDATA #IMPLIED
        valid      CDATA #IMPLIED
        id         ID    #IMPLIED
        kind       CDATA #IMPLIED               "                    >
        

<!--                    uml related information                    -->
<!--                    presently only use cases                   -->

<!ELEMENT  uml          ((classinfo|usecase)*)                       >

<!--                    Class information                          -->
<!--                    textual overview of classes                -->
<!ELEMENT  classinfo    (title, summary, attribute*, operation*,
                         invariant*, note*, related*  )              >
<!ATTLIST  classinfo
         %genattr;
>
<!--                    title                                      -->
<!ELEMENT  title        (#PCDATA)                                    >

<!--                    summary                                    -->
<!ELEMENT  summary      (#PCDATA)                                    >

<!--                    Class attributes                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  attributes   ((attribute|note)*)                          >

<!--                    attribute                                  -->
<!ELEMENT  attribute    (#PCDATA)                                    >

<!--                    Usecase description (text)                 -->
<!ELEMENT  usecase      (title, summary, actor+, context?,
                           precondition, postcondition, input?, 
                           result?,  error*, sequence*, note*,
                           related* )                                >




<!--                    Note                                       -->
<!--                    any textual addition or explanation        -->
<!ELEMENT  note         (#PCDATA)                                    >

<!--                    Class operations                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  operations   ((operation|note)*)                          >

<!--                    Class operation                            -->
<!--                    not yet defined                            -->
<!ELEMENT  operation    (#PCDATA)                                    >

<!--                    Class invariants                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  invariants   ((invariant|note)*)                          >

<!--                    Class invariant                            -->
<!--                    not yet defined                            -->
<!ELEMENT  invariant    (#PCDATA)                                    >

<!--                    Notes                                      -->
<!--                    any sosequence of additions and
                        explanations                               -->
<!ELEMENT  notes        (note*)                                      >


<!--                    precondition                               -->
<!ELEMENT  precondition (#PCDATA)                                    >

<!--                    postcondition                              -->
<!ELEMENT  postcondition  (#PCDATA)                                  >

<!--                    error                                      -->
<!ELEMENT  error        (title?, summary?, precondition?,
                         postcondition?)                             >

<!--                    actor                                      -->
<!ELEMENT  actor       (#PCDATA)                                    >

<!--                    sequence                                   -->
<!ELEMENT  sequence     (title?,summary?,(item,note*)+)              >


<!--                    li                                         -->
<!ELEMENT  li           (#PCDATA)                                    >

<!--                    dt                                         -->
<!ELEMENT  dt           (#PCDATA)                                    >

<!--                    di                                         -->
<!ELEMENT  di           (#PCDATA)                                    >

<!--                    trigger                                    -->
<!ELEMENT  trigger      (#PCDATA)                                    >


<!--                    UML Glossary                               -->
<!--                    incomplete                                 -->
<!ELEMENT  glossary     (GlossEntry+)                                >


<!--                    Glossary entry                             -->
<!--                    incomplete                                 -->
<!ELEMENT  GlossEntry   (GlossTerm, Acronym?, Abbrev?,
                         (GlossSee | GlossDef+), GlossSeeAlso*)      >


<!--                    Term                                       -->
<!--                    a simple string?                           -->
<!ELEMENT  term         (#PCDATA)                                    >


<!--                    Docbook GlossTerm                          -->
<!--                    Term outside a Glossary that is defined in
                        some GlossEntry; term within a GlossEntry 
                        that is defined by that GlossEntry         -->
<!ELEMENT  GlossTerm    (#PCDATA)                                    >

<!--                    Docbook Acronym                            -->
<!--                    Pronounceable contraction of initials      -->
<!ELEMENT  Acronym      (#PCDATA)                                    >

<!--                    Docbook Abbrev                             -->
<!--                    Abbreviation, especially one followed by a
                        period                                     -->
<!ELEMENT  Abbrev       (#PCDATA)                                     >


<!--                    Docbook GlossSee               -->
<!--                    Cross-reference from one GlossEntry to
                        another                                    -->
<!ELEMENT  GlossSee     (#PCDATA|GlossTerm)*                   >

<!--                    Docbook GlossSeeAlso                       -->
<!--                    Cross-reference from one GlossDef to
                        another GlossEntry                         -->
<!ELEMENT  GlossSeeAlso (#PCDATA |  GlossTerm)*                   >


<!--                    Docbook GlossDef                           -->
<!--                    Definition attached to a GlossTerm in a
                        GlossEntry                                 -->
<!ELEMENT  GlossDef     (#PCDATA |  GlossTerm)*                   >


<!--                    Dialogue Interface description             -->
<!--                    Describes a GUI interface                  -->
<!ELEMENT  dialogue     (title, summary?, context?, data*, action*,
                         note*)                                      >
<!ATTLIST  dialogue
        %genattr;
>

<!--                    Context of action, interface               -->
<!--                    Describes context, usage, etc.             -->
<!ELEMENT  context      (#PCDATA)                                    >

<!--                    Data description                           -->
<!--                    Describes data elements of interfaces      -->
<!ELEMENT  data         (label, item, note?)                         >

<!--                    Input description                          -->
<!--                    Describes input data elements              -->
<!ELEMENT  input        (label, item, note?)*                        >

<!--                    Result description                         -->
<!--                    Describes resulting data elements          -->
<!ELEMENT  result       (label, item, note?)*                        >

<!--                    Descriptive Label                          -->
<!--                    Gives the name of data elements etc.       -->
<!ELEMENT  label        (#PCDATA)                                    >

<!--                    Description of Item                        -->
<!--                    Explains the item                          -->
<!ELEMENT  item         (#PCDATA)                                    >

<!--                    Action Description                         -->
<!--                    Associated Actions                         -->
<!ELEMENT  action       (subactions?, label, item, note?)            >

<!--                    Subaction references                       -->
<!--                    Gives actions that are not explained here
                        but possibly nested within the described
                        action                                     -->
<!ELEMENT  subactions   (#PCDATA)                                    >

<!--                    Related information                        -->
<!--                    Indicates related documents                -->
<!ELEMENT  related      (#PCDATA)                                    >

=== GNOME/pybliographer/doc/design/data/gloen_u.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE glossary SYSTEM '../txdata.dtd' >


<glossary buchstabe="U">

  <GlossEntry>
    <GlossTerm>      Uniform title
    </GlossTerm>

    <GlossDef>
      A <GlossTerm>heading</GlossTerm> that is used to
      <GlossTerm>collocate</GlossTerm> all
      <GlossTerm>manifestations</GlossTerm> of a
      <GlossTerm>work</GlossTerm>, or as <GlossTerm>collective uniform
      title</GlossTerm>, all (subclasses of) collections by an
      author. Compares to *<GlossTerm>GMD</GlossTerm> and German
      FST. Generalisation: <GlossTerm>Classifier</GlossTerm>.
    </GlossDef>

    <GlossSeeAlso>title</GlossSeeAlso>

  </GlossEntry>


</glossary>

=== GNOME/pybliographer/doc/design/data/gloen_e.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE glossary SYSTEM '../txdata.dtd' >


<glossary buchstabe="E">

  <GlossEntry>
    <GlossTerm>      Expression
    </GlossTerm>
    <GlossDef>
      An equivalence class of <GlossTerm>manifestations</GlossTerm>,
      which share certain characteristic dependencies.

      Examples are translations of a work, that are traditonally
      equipped with an <GlossTerm>uniform title</GlossTerm> composed
      of the uniform title of the original work and a language
      indication: Shakespeare, William: Othello &lt;ger.&gt;

      Other common cases are pieces of music which can be expressed as
      scores or recorded performances, etc.
    </GlossDef>
    <GlossSeeAlso>Work</GlossSeeAlso>
    <GlossSeeAlso>Manifestation</GlossSeeAlso>
    <GlossSeeAlso>Heading</GlossSeeAlso>
  </GlossEntry>

 


</glossary>

=== GNOME/pybliographer/doc/design/data/uc058.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc018' type='standard' lang='en' >

    <title>Control external connections
    </title>

    <summary>Control parameters for cooperation with word processsors
    or the like.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc013.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc013' type='standard' lang='en' >

    <title>Manage references
    </title>

    <summary>The references that form part of a certain reference list
    (i.e. that are cited by a cerain document) are collected.

    Sometimes databsase services already produce such lists, there
    are also projects to extract these data from documents (OpCit).
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc000.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc000' type='standard' lang='en' >

    <title>
    </title>

    <summary>
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc015.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc011' type='standard' lang='en' >

    <title>Make a bibliography (reference list)
    </title>

    <summary>This is the equivalent of running bibtex.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/dlg_query1.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE dialogue SYSTEM '../txdata.dtd' >


<dialogue n="query1">

  <title>Standard Search</title>
  <summary>
  </summary>
  <context>
    General use -- this is in many cases the most frequently used
    interface component at all.
  </context>

  <data>
    <label>database</label>
    <item>The database or folder etc. the query is executed against.
      The type should be indicated.
    </item>
  </data>
  <data>
    <label>q.string</label>
    <item>The string to search for</item>
  </data>
  <data>
    <label>q.regexp</label>
    <item>Allow regexp search, if possible (les imbeciles ne sont pas
      admis)
    </item> 
  </data>
  <data>
    <label>q.field</label>
    <item>The (gross) category we search in (usually "all").
    </item>
  </data>
  <action>
    <subactions>
      browse index; complete field; read help; examine prevous
      results;
    </subactions>
  </action>
  <action>
    <label>Cancel</label>
    <item>(special case when this is the main window)
    </item>
  </action>
  <action>
    <label>Search</label>
    <item>Execute search</item>
  </action>
  <action>
    <label>Expert search</label>
    <item>A dialogue is opened which displays extended search options.
    </item>
  </action>
  <note>
    For an example of a visually appealing query dialogue see the
    aleph500 main window at http://obelix.ub.uni-siegen.de/

    It clearly labels the database against which the search will be
    executed.

    </note>
  <note>
    It is possible to have more than one query string in this
    dialogue; but perhaps a simple dialogue is more appealing here?
  </note>
</dialogue>

=== GNOME/pybliographer/doc/design/data/uc016.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc016' type='standard' lang='en' >

    <title>Operate on result sets
    </title>

    <summary>Result sets are a fundamental UI element, in addition one
    can use them for set algebra. 
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>
