=== GNOME/pybliographer/doc/design/txdata.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!--                    General attributes                         -->
<!--                    Attributes common to most elements         -->
<!ENTITY % genattr      "
        n          CDATA #IMPLIED
        type       CDATA #IMPLIED
        valid      CDATA #IMPLIED
        id         ID    #IMPLIED
        kind       CDATA #IMPLIED               "                    >
        

<!--                    uml related information                    -->
<!--                    presently only use cases                   -->

<!ELEMENT  uml          ((classinfo|usecase)*)                       >

<!--                    Class information                          -->
<!--                    textual overview of classes                -->
<!ELEMENT  classinfo    (title, summary, attribute*, operation*,
                         invariant*, note*, related*  )              >
<!ATTLIST  classinfo
         %genattr;
>
<!--                    title                                      -->
<!ELEMENT  title        (#PCDATA)                                    >

<!--                    summary                                    -->
<!ELEMENT  summary      (#PCDATA)                                    >

<!--                    Class attributes                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  attributes   ((attribute|note)*)                          >

<!--                    attribute                                  -->
<!ELEMENT  attribute    (#PCDATA)                                    >

<!--                    Usecase description (text)                 -->
<!ELEMENT  usecase      (title, summary, actor+, context?,
                           precondition, postcondition, input?, 
                           result?,  error*, sequence*, note*,
                           related* )                                >




<!--                    Note                                       -->
<!--                    any textual addition or explanation        -->
<!ELEMENT  note         (#PCDATA)                                    >

<!--                    Class operations                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  operations   ((operation|note)*)                          >

<!--                    Class operation                            -->
<!--                    not yet defined                            -->
<!ELEMENT  operation    (#PCDATA)                                    >

<!--                    Class invariants                           -->
<!--                    may be incomplete                          -->
<!ELEMENT  invariants   ((invariant|note)*)                          >

<!--                    Class invariant                            -->
<!--                    not yet defined                            -->
<!ELEMENT  invariant    (#PCDATA)                                    >

<!--                    Notes                                      -->
<!--                    any sosequence of additions and
                        explanations                               -->
<!ELEMENT  notes        (note*)                                      >


<!--                    precondition                               -->
<!ELEMENT  precondition (#PCDATA)                                    >

<!--                    postcondition                              -->
<!ELEMENT  postcondition  (#PCDATA)                                  >

<!--                    error                                      -->
<!ELEMENT  error        (title?, summary?, precondition?,
                         postcondition?)                             >

<!--                    actor                                      -->
<!ELEMENT  actor       (#PCDATA)                                    >

<!--                    sequence                                   -->
<!ELEMENT  sequence     (title?,summary?,(item,note*)+)              >


<!--                    li                                         -->
<!ELEMENT  li           (#PCDATA)                                    >

<!--                    dt                                         -->
<!ELEMENT  dt           (#PCDATA)                                    >

<!--                    di                                         -->
<!ELEMENT  di           (#PCDATA)                                    >

<!--                    trigger                                    -->
<!ELEMENT  trigger      (#PCDATA)                                    >


<!--                    UML Glossary                               -->
<!--                    incomplete                                 -->
<!ELEMENT  glossary     (GlossEntry+)                                >


<!--                    Glossary entry                             -->
<!--                    incomplete                                 -->
<!ELEMENT  GlossEntry   (GlossTerm, Acronym?, Abbrev?,
                         (GlossSee | GlossDef+), GlossSeeAlso*)      >


<!--                    Term                                       -->
<!--                    a simple string?                           -->
<!ELEMENT  term         (#PCDATA)                                    >


<!--                    Docbook GlossTerm                          -->
<!--                    Term outside a Glossary that is defined in
                        some GlossEntry; term within a GlossEntry 
                        that is defined by that GlossEntry         -->
<!ELEMENT  GlossTerm    (#PCDATA)                                    >

<!--                    Docbook Acronym                            -->
<!--                    Pronounceable contraction of initials      -->
<!ELEMENT  Acronym      (#PCDATA)                                    >

<!--                    Docbook Abbrev                             -->
<!--                    Abbreviation, especially one followed by a
                        period                                     -->
<!ELEMENT  Abbrev       (#PCDATA)                                     >


<!--                    Docbook GlossSee               -->
<!--                    Cross-reference from one GlossEntry to
                        another                                    -->
<!ELEMENT  GlossSee     (#PCDATA|GlossTerm)*                   >

<!--                    Docbook GlossSeeAlso                       -->
<!--                    Cross-reference from one GlossDef to
                        another GlossEntry                         -->
<!ELEMENT  GlossSeeAlso (#PCDATA |  GlossTerm)*                   >


<!--                    Docbook GlossDef                           -->
<!--                    Definition attached to a GlossTerm in a
                        GlossEntry                                 -->
<!ELEMENT  GlossDef     (#PCDATA |  GlossTerm)*                   >


<!--                    Dialogue Interface description             -->
<!--                    Describes a GUI interface                  -->
<!ELEMENT  dialogue     (title, summary?, context?, data*, action*,
                         note*)                                      >
<!ATTLIST  dialogue
        %genattr;
>

<!--                    Context of action, interface               -->
<!--                    Describes context, usage, etc.             -->
<!ELEMENT  context      (#PCDATA)                                    >

<!--                    Data description                           -->
<!--                    Describes data elements of interfaces      -->
<!ELEMENT  data         (label, item, note?)                         >

<!--                    Input description                          -->
<!--                    Describes input data elements              -->
<!ELEMENT  input        (label, item, note?)*                        >

<!--                    Result description                         -->
<!--                    Describes resulting data elements          -->
<!ELEMENT  result       (label, item, note?)*                        >

<!--                    Descriptive Label                          -->
<!--                    Gives the name of data elements etc.       -->
<!ELEMENT  label        (#PCDATA)                                    >

<!--                    Description of Item                        -->
<!--                    Explains the item                          -->
<!ELEMENT  item         (#PCDATA)                                    >

<!--                    Action Description                         -->
<!--                    Associated Actions                         -->
<!ELEMENT  action       (subactions?, label, item, note?)            >

<!--                    Subaction references                       -->
<!--                    Gives actions that are not explained here
                        but possibly nested within the described
                        action                                     -->
<!ELEMENT  subactions   (#PCDATA)                                    >

<!--                    Related information                        -->
<!--                    Indicates related documents                -->
<!ELEMENT  related      (#PCDATA)                                    >

=== GNOME/pybliographer/doc/design/data/uc017.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc017' type='standard' lang='en' >

    <title>Organise folders and Databases
    </title>

    <summary>The Pybliographer database is logically organised as a
    folder hierarchy; external databases are listed seperately. Those
    lists and the associated entries may need user attention.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc024.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc024' type='standard' lang='en' >

    <title>Search and replace records
    </title>

    <summary>Perform a (regexp) search-and-replace action on a result
    set.

    It is important that the replacing can be suitably limited. 
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc011.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc006' type='standard' lang='en' >

    <title>Select a database
    </title>

    <summary>All processing is against a database (?).
    A choice is given, even if a default database is defined.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/gloen_p.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE glossary SYSTEM '../txdata.dtd' >


<glossary buchstabe="P">


  <GlossEntry>
    <GlossTerm>Person</GlossTerm>
    <GlossDef>
      An individual (or whoever appears to be an individual, Nicholas
      Bourbaki, say). There are two ways to handle persons in
      bibliography, as individuals or as names. For searching, the
      latter is usually sufficient, so this the German usage until the
      present. The American usage is informed by the idea of the
      dictionary catalogue, where works about an author are listed
      next to works by him, requiring the use of individualised
      entries from early on.

      No rules without exception. If there is insufficient information
      (or interest) one may eschew the work needed for determining the
      correct author entry; on the other hand, for the purpose of
      subject headings, one buildt a German authority file, too; with
      funnily different rules.
      
    </GlossDef>
    <GlossSeeAlso>Collective person</GlossSeeAlso>
  </GlossEntry>

  <GlossEntry>
    <GlossTerm>Publication</GlossTerm>
    <GlossDef>
      The preparation (e.g. typesetting), manufacture and distribution
      of copies of an item (manifestation). Generally done by a
      separate commercial entity, the publisher. For items that are
      not conventionnally printed, this is rapidly becoming a
      problematic notion. For material that is not somehow
      manufactured, but, say only made available as a computer file,
      the notion is fundamentally flawed, it appears.
    </GlossDef>
  </GlossEntry>


  <GlossEntry>
    <GlossTerm>Publication Statement</GlossTerm>
    <GlossDef>Contains place of publication, publisher, date (i.e.,
    year) of publication. Required for published materials. Also
    called Imprint. </GlossDef>
  </GlossEntry>

  <GlossEntry>
    <GlossTerm>Publisher</GlossTerm>
    <GlossDef>
      Someone who manufactures and distributes copies of an item
      (manifestation). ISBD and MARC allow for a printer in place of
      or addition to the publisher. 
    </GlossDef>
  </GlossEntry>

</glossary>

=== GNOME/pybliographer/doc/design/data/uc003.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc003' type='standard' lang='en' >

    <title>Expert Search
    </title>

    <summary>A so called expert search is prepared and executed
    (perhaps it is stored or reused). 
    </summary>
    <actor></actor>
    <context></context>
    <precondition>None</precondition>
    <postcondition>A result set is presented; or an error indication.
    </postcondition>
    <error>
    </error>
    <sequence>
    <item>A database is selected</item>
    <item>The possible search criteria are presented</item>
    <item>A choice is made of suitable criteria, and the search
      accordingly formulated </item>
    <item>Alternatively it may be formulated in text form, depending
      on the database</item>
    <item>It is sent, and the result or an error indication is
      received.</item>    
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc005.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc005' type='standard' lang='en' >

    <title>Add an note to an item
    </title>

    <summary>A note is added to an item.
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note> -- that should be possible
      even for the output stage on a per user basis.
    </note>
    
  <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc055.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc015' type='standard' lang='en' >

    <title>User administration
    </title>

    <summary>Modify preferences and possibly access rights on a per
    user basis. [pro memoria: must not assume that there will be only
    one user]
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>

=== GNOME/pybliographer/doc/design/data/uc012.xml
<?xml version="1.0" encoding="iso8859-1" ?>

<!DOCTYPE usecase SYSTEM '../txdata.dtd' >



  <usecase n='uc012' type='standard' lang='en' >

    <title>Cite a reference
    </title>

    <summary>Place a marker in a document to indicate a cited
    reference.

    This function needs the collaboration of the document
    processor/editor. 
    </summary>
    <actor></actor>
    <situation></situation>
    <precondition></precondition>
    <postcondition></postcondition>
    <error>
    </error>
    <sequence>
    </sequence>
    <note></note>
    <related></related>

  </usecase>
